#!/bin/bash

# 1 Put this script inside /usr/local/bin
# 2 Then run command alias ss="pass"
# 3 Install sshpass command

user=$(echo $1 | awk -F "@" '{print $1}')
host=$(echo $1 | awk -F "@" '{print $2}')

knowhost=$(cat ~/.ssh/known_hosts| grep  -o $host)
if [[ $knowhost == $host ]]
then
        if [ echo $? >= 1 ]
	then
		ssh $user@$host  mkdir /$user.ssh/
	fi
	ssh $user@$host
else
	read -sp "$user@$host's password:" password
	checkFolderExist=$(sshpass -p $password ssh $user@$host 'test -d ~/.ssh/ && echo "exist" || echo "not exist"')
	if [[ $checkFolderExist == 'exist' ]]; then
		cat ~/.ssh/id_rsa.pub | (sshpass -p $password ssh $user@$host "cat >> ~/.ssh/authorized_keys")
		ssh $user@$host
	else
		sshpass -p $password ssh $user@$host 'mkdir ~/.ssh'
		cat ~/.ssh/id_rsa.pub | (sshpass -p $password ssh $user@$host "cat >> ~/.ssh/authorized_keys")
		ssh $user@$host
	fi
fi
